CREATE TABLE STOCK 
(
  SYMBOL VARCHAR2(20) NOT NULL 
, OUTSTANDINGSHARES LONG 
, PRICETOEARNING DOUBLE PRECISION 
, EBITDA DOUBLE PRECISION 
, BOOKVAUEPERSHARE DOUBLE PRECISION 
, ANNUALTARGETPRICE DOUBLE PRECISION 
, INSERT_TIMESTAMP TIMESTAMP NOT NULL 
);

ALTER TABLE STOCK
ADD CONSTRAINT STOCK_UK1 UNIQUE 
(
  INSERT_TIMESTAMP 
, SYMBOL 
)
ENABLE;
